<header>
    <a href="#my_photo" class="logo header_element"><img id="logo" src="images/logo.png" alt="Logo" width="100" height="100"></a> <!--link to homepage-->
    <nav class="navigation">
        <a class="header_element" href="#professional">SPECIALTY</a>
        <a class="header_element" href="#portfolio">PORTFOLIO</a>
        <a class="header_element" href="#experience">EXPERIENCE</a>
        <a class="header_element" href="#contact">CONTACT</a>
    </nav>
</header>